/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projeto.mercado.Telas;

import java.util.HashSet;
import java.util.Set;
import javax.swing.JOptionPane;

/**
 *
 * @author lucas
 */
public class TelaLogin extends javax.swing.JFrame {

    /**
     * Creates new form TelaLogin
     */
    public TelaLogin() {
        initComponents();
        setSize(1090,720);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        senha = new javax.swing.JLabel();
        nome = new javax.swing.JLabel();
        NOME = new javax.swing.JTextField();
        SENHA = new javax.swing.JPasswordField();
        butaoOK = new javax.swing.JButton();
        JLfundo = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/user.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(840, 20, 140, 130);

        senha.setFont(new java.awt.Font("Impact", 0, 24)); // NOI18N
        senha.setText("SENHA:");
        getContentPane().add(senha);
        senha.setBounds(720, 210, 70, 31);

        nome.setFont(new java.awt.Font("Impact", 0, 24)); // NOI18N
        nome.setText("NOME:");
        getContentPane().add(nome);
        nome.setBounds(720, 160, 60, 31);

        NOME.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NOMEActionPerformed(evt);
            }
        });
        getContentPane().add(NOME);
        NOME.setBounds(800, 160, 210, 30);

        SENHA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SENHAActionPerformed(evt);
            }
        });
        getContentPane().add(SENHA);
        SENHA.setBounds(800, 210, 210, 30);

        butaoOK.setFont(new java.awt.Font("Impact", 0, 24)); // NOI18N
        butaoOK.setText("LOGAR");
        butaoOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butaoOKActionPerformed(evt);
            }
        });
        getContentPane().add(butaoOK);
        butaoOK.setBounds(800, 260, 210, 40);

        JLfundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/login_projeto.png"))); // NOI18N
        getContentPane().add(JLfundo);
        JLfundo.setBounds(0, -40, 1100, 800);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1080, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 720, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1080, 720);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NOMEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NOMEActionPerformed

        
    }//GEN-LAST:event_NOMEActionPerformed

    private void butaoOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butaoOKActionPerformed
        String Nomim = NOME.getText();
        String Seinha = SENHA.getText();
               if((Nomim.equals("lucas")) && (Seinha.equals("123"))){
                   TelaADM tela = new TelaADM();
                   tela.setVisible(true);
               }else{
                   JOptionPane.showMessageDialog(null, "Nome ou Senha invalido");
                   
               }
        
    }//GEN-LAST:event_butaoOKActionPerformed

    private void SENHAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SENHAActionPerformed
        
    }//GEN-LAST:event_SENHAActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JLfundo;
    private javax.swing.JTextField NOME;
    private javax.swing.JPasswordField SENHA;
    private javax.swing.JButton butaoOK;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel nome;
    private javax.swing.JLabel senha;
    // End of variables declaration//GEN-END:variables
}
