/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projeto.mercado.Telas;

/**
 *
 * @author lucas
 */
public class TelaADM extends javax.swing.JFrame {

    /**
     * Creates new form TelaADM
     */
    public TelaADM() {
        initComponents();
        initComponents();
        setSize(1090,720);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botaoRend = new javax.swing.JButton();
        botaoMerca = new javax.swing.JButton();
        fundo = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        botaoRend.setFont(new java.awt.Font("Impact", 0, 24)); // NOI18N
        botaoRend.setText("Rendimento");
        botaoRend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoRendActionPerformed(evt);
            }
        });
        getContentPane().add(botaoRend);
        botaoRend.setBounds(170, 0, 180, 50);

        botaoMerca.setFont(new java.awt.Font("Impact", 0, 24)); // NOI18N
        botaoMerca.setText("Mercadoria");
        botaoMerca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoMercaActionPerformed(evt);
            }
        });
        getContentPane().add(botaoMerca);
        botaoMerca.setBounds(0, 0, 180, 50);

        fundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/login_projeto.png"))); // NOI18N
        getContentPane().add(fundo);
        fundo.setBounds(0, 0, 1080, 720);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1080, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 720, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1080, 720);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoRendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoRendActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botaoRendActionPerformed

    private void botaoMercaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoMercaActionPerformed
        mercadoria Mer1 = new mercadoria();
        Mer1.setVisible(true);
    }//GEN-LAST:event_botaoMercaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaADM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaADM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaADM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaADM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaADM().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoMerca;
    private javax.swing.JButton botaoRend;
    private javax.swing.JLabel fundo;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
